name = "olang"
grammar = "olang"
path_suffixes = ["ol"]
line_comments = ["// "]
brackets = [
  { start = "{", end = "}", close = true, newline = true },
  { start = "(", end = ")", close = true, newline = false },
  { start = "[", end = "]", close = true, newline = false },
  { start = "\"", end = "\"", close = true, newline = false, not_in = ["string"] },
]
tab_size = 4
