//! Phase 2 integration tests: the stats namespace from olang source,
//! with values pinned against scipy (constants generated by the snippet
//! in olang-ods/tests/stats.rs) and tier transparency for the flows
//! that promote.


use olang::ast::Value;
use olang::{Interpreter, Parser};

fn with_big_stack<T: Send + 'static>(f: impl FnOnce() -> T + Send + 'static) -> T {
    std::thread::Builder::new()
        .stack_size(256 * 1024 * 1024)
        .spawn(f)
        .expect("spawn")
        .join()
        .expect("join")
}

fn eval(source: &str, tier_threshold: Option<u32>) -> Result<Value, String> {
    let source = source.to_string();
    with_big_stack(move || {
        let parser = Parser::new();
        let program = parser.parse(&source).map_err(|e| e.to_string())?;
        let mut interpreter = Interpreter::new();
        if let Some(threshold) = tier_threshold {
            interpreter.enable_bytecode_tier(threshold, false);
        }
        interpreter.eval_program(program).map_err(|e| e.to_string())
    })
}

fn assert_tier_transparent(source: &str) -> Result<Value, String> {
    let interpreted = eval(source, None);
    let promoted = eval(source, Some(2));
    match (&interpreted, &promoted) {
        (Ok(a), Ok(b)) => assert_eq!(a, b, "promotion changed the result\n  source: {}", source),
        (Err(_), Err(_)) => {}
        _ => panic!(
            "promotion changed success/failure\n  interpreted: {:?}\n  promoted: {:?}",
            interpreted, promoted
        ),
    }
    interpreted
}

fn as_float(v: &Value) -> f64 {
    match v {
        Value::Float(x) => *x,
        Value::Integer(x) => *x as f64,
        other => panic!("expected a number, got {:?}", other),
    }
}

fn close(got: f64, want: f64, tol: f64) {
    assert!(
        (got - want).abs() <= tol * (1.0 + want.abs()),
        "got {}, want {}",
        got,
        want
    );
}

#[test]
fn distribution_functions_from_source() {
    let result = assert_tier_transparent(
        r#"
        [
            stats.norm.cdf(1.96, 0.0, 1.0),
            stats.norm.ppf(0.975, 0.0, 1.0),
            stats.t.ppf(0.975, 7),
            stats.chi2.ppf(0.95, 4),
            stats.f.cdf(2.5, 3, 10)
        ]
        "#,
    )
    .unwrap();
    let items = match result {
        Value::List(items) => items,
        other => panic!("expected list, got {:?}", other),
    };
    close(as_float(&items[0]), 0.9750021048517795, 1e-9);
    close(as_float(&items[1]), 1.959963984540054, 1e-8);
    close(as_float(&items[2]), 2.364624251592784, 1e-8);
    close(as_float(&items[3]), 9.487729036781154, 1e-8);
    close(as_float(&items[4]), 0.8809604373417219, 1e-9);
}

#[test]
fn t_test_and_describe_from_source() {
    // scipy: ttest_ind(a, b, equal_var=False) → t=4.15548, p=0.0013163
    let result = eval(
        r#"
        let a = ods.series([5.1, 4.9, 6.2, 5.7, 5.5, 4.8, 5.9, 6.1])
        let b = ods.series([4.2, 4.8, 4.5, 5.0, 4.4, 4.1, 4.9])
        let r = stats.t_test(a, b)
        let d = stats.describe(a)
        [map_get(r, "t"), map_get(r, "p_value"), map_get(d, "count"), map_get(d, "median")]
        "#,
        None,
    )
    .unwrap();
    let items = match result {
        Value::List(items) => items,
        other => panic!("expected list, got {:?}", other),
    };
    close(as_float(&items[0]), 4.15548385691924, 1e-9);
    close(as_float(&items[1]), 0.0013163190997012772, 1e-8);
    assert_eq!(items[2], Value::Integer(8));
    close(as_float(&items[3]), 5.6, 1e-9);
}

#[test]
fn one_sample_t_test_by_scalar_second_argument() {
    let result = eval(
        r#"
        let a = ods.series([5.1, 4.9, 6.2, 5.7, 5.5, 4.8, 5.9, 6.1])
        let r = stats.t_test(a, 5.0)
        [map_get(r, "t"), map_get(r, "df")]
        "#,
        None,
    )
    .unwrap();
    let items = match result {
        Value::List(items) => items,
        other => panic!("expected list, got {:?}", other),
    };
    close(as_float(&items[0]), 2.7406110459365625, 1e-9);
    close(as_float(&items[1]), 7.0, 1e-9);
}

#[test]
fn chi2_and_corr_from_source() {
    let result = eval(
        r#"
        let obs = ods.series([18.0, 22.0, 27.0, 33.0])
        let expected = ods.series([25.0, 25.0, 25.0, 25.0])
        let c = stats.chi2_test(obs, expected)
        let x = ods.series([1.0, 2.0, 3.0, 4.0, 5.0, 6.0])
        let y = ods.series([2.1, 3.9, 6.2, 8.1, 9.8, 12.3])
        [map_get(c, "chi2"), map_get(c, "p_value"), stats.corr(x, y), stats.cov(x, y)]
        "#,
        None,
    )
    .unwrap();
    let items = match result {
        Value::List(items) => items,
        other => panic!("expected list, got {:?}", other),
    };
    close(as_float(&items[0]), 5.04, 1e-9);
    close(as_float(&items[1]), 0.16889147065779933, 1e-8);
    close(as_float(&items[2]), 0.9988210605417898, 1e-9);
    close(as_float(&items[3]), 7.060000000000001, 1e-9);
}

#[test]
fn lm_from_source_matches_reference() {
    let result = eval(
        r#"
        let x1 = ods.series([1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0])
        let x2 = ods.series([2.0, 1.0, 4.0, 3.0, 6.0, 5.0, 8.0, 7.0])
        let y = ods.series([3.1, 4.2, 7.3, 7.9, 11.2, 11.8, 15.3, 15.9])
        let fit = stats.lm(y, [x1, x2])
        [
            ods.to_list(map_get(fit, "coef")),
            map_get(fit, "r2"),
            map_get(fit, "n"),
            ods.get(map_get(fit, "p_value"), 1)
        ]
        "#,
        None,
    )
    .unwrap();
    let items = match result {
        Value::List(items) => items,
        other => panic!("expected list, got {:?}", other),
    };
    let coef = match &items[0] {
        Value::List(c) => c,
        other => panic!("expected coef list, got {:?}", other),
    };
    close(as_float(&coef[0]), 0.6437500000000069, 1e-8);
    close(as_float(&coef[1]), 1.3562499999999995, 1e-8);
    close(as_float(&coef[2]), 0.631249999999999, 1e-8);
    close(as_float(&items[1]), 0.999301056268897, 1e-9);
    assert_eq!(items[2], Value::Integer(8));
    close(as_float(&items[3]), 1.874213966504236e-06, 1e-6);
}

#[test]
fn lm_accepts_single_regressor_without_list() {
    let result = eval(
        r#"
        let x = ods.series([1.0, 2.0, 3.0, 4.0])
        let y = ods.series([2.1, 3.9, 6.1, 8.0])
        let fit = stats.lm(y, x)
        ods.len(map_get(fit, "coef"))
        "#,
        None,
    );
    assert_eq!(result, Ok(Value::Integer(2)));
}

// NOTE: this is the single test in this binary allowed to touch the
// random module. The RNG is process-global and the test harness runs
// tests on parallel threads, so two RNG-using tests would interleave
// draws and flake — seed determinism and sampled moments live together.
#[test]
fn sampling_respects_random_seed_and_moments_are_sane() {
    let result = eval(
        r#"
        random.seed(42)
        let a = stats.norm.sample(5, 0.0, 1.0)
        random.seed(42)
        let b = stats.norm.sample(5, 0.0, 1.0)
        let c = stats.norm.sample(5, 0.0, 1.0)
        [a == b, a == c, ods.len(a), typeof(a)]
        "#,
        None,
    )
    .unwrap();
    assert_eq!(
        result,
        Value::List(
            vec![
                Value::Boolean(true),
                Value::Boolean(false),
                Value::Integer(5),
                Value::String("Series".to_string().into()),
            ]
            .into()
        )
    );

    // Sampled moments: not a distribution test — just that inverse
    // transform + seed wiring produce the right location/scale at n=20k.
    let result = eval(
        r#"
        random.seed(7)
        let s = stats.norm.sample(20000, 10.0, 2.0)
        [ods.mean(s), ods.std(s)]
        "#,
        None,
    )
    .unwrap();
    let items = match result {
        Value::List(items) => items,
        other => panic!("expected list, got {:?}", other),
    };
    close(as_float(&items[0]), 10.0, 0.02);
    close(as_float(&items[1]), 2.0, 0.02);
}

#[test]
fn stats_error_paths_are_informative() {
    let err = eval("stats.t_test(3, 4)", None).unwrap_err();
    assert!(err.contains("must be a Series"), "got: {}", err);
    let err = eval("stats.norm.ppf(1.5, 0.0, 1.0)", None).unwrap_err();
    assert!(err.contains("[0, 1]"), "got: {}", err);
    let err = eval(
        "stats.lm(ods.series([1.0, 2.0]), ods.series([1.0, 2.0]))",
        None,
    )
    .unwrap_err();
    assert!(err.contains("more complete rows"), "got: {}", err);
}
