// Auto-generated index file for examples/utils
// This file automatically aggregates exports from all modules in this directory
// Generated by Olang Feature 5: Automatic Index Files

use math { calculate_average, square, cube }
use string { format_name, trim_spaces, to_uppercase }
use validation { is_email, is_phone, is_not_empty, ValidationResult }

// All exports are automatically available through the individual module imports above
// This allows 'use utils { function_name }' to work by importing from this index
