//! climate — a real data-science workstream on real downloaded data.
//!
//! Eight stages, end to end: fetch Our World in Data's CO2 and energy
//! datasets (cached under data/), prepare country and world views,
//! run the analyses, and write a self-contained report — markdown,
//! SVG charts, derived CSVs — into out/. Both directories are
//! regenerated by the run and ignored by git.
//!
//! Run:  olang run main.ol

use lib.fetch { fetch }
use lib.prep { countries, world, latest_covered_year, cross_section }
use lib.report { table, chart, derived_csv, write }

let t0 = time.monotonic_ms()
let t = cell(time.monotonic_ms())
fn stage(name, note) = {
    let now = time.monotonic_ms()
    println(`[${name}] ${now - cell.get(t)} ms — ${note}`)
    cell.set(t, now)
}

let blocks = cell(["# Climate and energy — the workstream report",
    `Generated ${dates.today()} by examples/climate/main.ol.`])
fn section(title, body) =
    cell.set(blocks, concat(cell.get(blocks), ["## " + title, body]))

// ── 1. fetch ─────────────────────────────────────────────────────────
println("fetching datasets (cached after the first run)...")
let co2_file = unwrap(fetch(
    "https://raw.githubusercontent.com/owid/co2-data/master/owid-co2-data.csv",
    fs.join("data", "owid-co2-data.csv"), 5000000))
let energy_file = unwrap(fetch(
    "https://raw.githubusercontent.com/owid/energy-data/master/owid-energy-data.csv",
    fs.join("data", "owid-energy-data.csv"), 3000000))
stage("fetch", `co2 ${map_get(co2_file, "bytes")} bytes (cached=${map_get(co2_file, "cached")}), energy ${map_get(energy_file, "bytes")} bytes (cached=${map_get(energy_file, "cached")})`)

// ── 2. load ──────────────────────────────────────────────────────────
let co2_raw = unwrap(ods.read_csv_file(map_get(co2_file, "path")))
let energy_raw = unwrap(ods.read_csv_file(map_get(energy_file, "path")))
stage("load", `co2 ${ods.n_rows(co2_raw)}x${ods.n_cols(co2_raw)}, energy ${ods.n_rows(energy_raw)}x${ods.n_cols(energy_raw)}`)

// ── 3. prep ──────────────────────────────────────────────────────────
let co2 = ods.select(co2_raw, ["country", "year", "iso_code", "population",
    "gdp", "co2", "co2_per_capita", "co2_per_gdp", "share_global_co2",
    "coal_co2", "oil_co2", "gas_co2"])
let energy = ods.select(energy_raw, ["country", "year", "iso_code",
    "population", "primary_energy_consumption", "energy_per_capita",
    "renewables_share_energy", "fossil_share_energy", "low_carbon_share_energy"])
let co2_countries = countries(co2)
let energy_countries = countries(energy)
let co2_world = world(co2)
unwrap(fs.create_dir_all("out"))
stage("prep", `countries: co2 ${ods.n_rows(co2_countries)}, energy ${ods.n_rows(energy_countries)}; world ${ods.n_rows(co2_world)} rows`)

// ── 4. global trajectory ─────────────────────────────────────────────
let world_recent = ods.sort_by(ods.filter(co2_world, co2_world["year"] >= 1950), "year", false)
let world_years = ods.to_list(world_recent["year"])
let world_co2 = ods.to_list(world_recent["co2"])
let peak_year = ods.to_list(ods.sort_by(world_recent, "co2", true)["year"])[0]
let co2_series = world_recent["co2"]
let prev = ods.shift(co2_series, 1)
let pct = (co2_series - prev) / prev
let growth = ods.rolling(pct, 10, "mean")
let latest_growth = math.round(ods.to_list(growth)[len(world_years) - 1] * 10000.0) / 100.0
let traj_svg = plot.line(world_recent["year"], world_recent["co2"],
    #{ "title": "World CO2 emissions, 1950—", "x_label": "year", "y_label": "Mt CO2" })
section("Global trajectory",
    `World emissions peaked (so far) in **${peak_year}**; the trailing 10-year mean growth rate is **${latest_growth}% per year**.` + "\n\n" + chart("world-co2.svg", traj_svg))
stage("trajectory", `peak ${peak_year}, 10y growth ${latest_growth}%`)

// ── 5. top emitters ──────────────────────────────────────────────────
let co2_year = latest_covered_year(co2_countries, "co2", 150)
let latest = cross_section(co2_countries, co2_year,
    ["country", "co2", "co2_per_capita", "share_global_co2"])
let top = ods.head(ods.sort_by(latest, "co2", true), 15)
let top_share = math.round(ods.sum(ods.head(ods.sort_by(latest, "co2", true), 10)["share_global_co2"]) * 10.0) / 10.0
let bar_svg = plot.bar(top["country"], top["co2"],
    #{ "title": `Top emitters, ${co2_year}`, "y_label": "Mt CO2" })
section(`Top emitters (${co2_year})`,
    `The ten largest emitters account for **${top_share}%** of global CO2.` + "\n\n" + table(top, 15) + "\n\n" + chart("top-emitters.svg", bar_svg))
stage("emitters", `year ${co2_year}, top-10 share ${top_share}%`)

// ── 6. decoupling ────────────────────────────────────────────────────
let gdp_year = latest_covered_year(co2_countries, "gdp", 100)
let start_year = gdp_year - 10
let now_slice = cross_section(co2_countries, gdp_year, ["country", "gdp", "co2"])
let then_slice = cross_section(co2_countries, start_year, ["country", "gdp", "co2"])
let then_named = ods.rename(then_slice, #{ "gdp": "gdp_then", "co2": "co2_then" })
let paired = ods.join(now_slice, then_named, "country")
// GDP columns infer as Int; the ratios must not truncate.
let gdp_now = ods.cast(paired["gdp"], "Float")
let gdp_then = ods.cast(paired["gdp_then"], "Float")
let with_gdp_growth = ods.with_column(paired, "gdp_change",
    (gdp_now - gdp_then) / gdp_then)
let with_both = ods.with_column(with_gdp_growth, "co2_change",
    (with_gdp_growth["co2"] - with_gdp_growth["co2_then"]) / with_gdp_growth["co2_then"])
let grew = ods.filter(with_both, with_both["gdp_change"] > 0.0)
let decoupled = ods.sort_by(ods.filter(grew, grew["co2_change"] < 0.0), "co2_change", false)
let dec_view = ods.select(decoupled, ["country", "gdp_change", "co2_change"])
let dec_rows = derived_csv("decoupling.csv", dec_view)
section(`Absolute decoupling (${start_year}—${gdp_year})`,
    `**${dec_rows} countries** grew GDP while cutting CO2 over the decade. The deepest cuts:` + "\n\n" + table(dec_view, 10) + "\n\nFull list: decoupling.csv")
stage("decoupling", `${dec_rows} countries over ${start_year}-${gdp_year}`)

// ── 7. energy transition ─────────────────────────────────────────────
let ren_year = latest_covered_year(energy_countries, "renewables_share_energy", 50)
let ren_now = cross_section(energy_countries, ren_year, ["country", "renewables_share_energy"])
let ren_then = ods.rename(cross_section(energy_countries, 2000, ["country", "renewables_share_energy"]),
    #{ "renewables_share_energy": "share_2000" })
let ren = ods.join(ren_now, ren_then, "country")
let ren_delta = ods.with_column(ren, "gain",
    ren["renewables_share_energy"] - ren["share_2000"])
let movers = ods.head(ods.sort_by(ren_delta, "gain", true), 15)
let movers_view = ods.select(movers, ["country", "share_2000", "renewables_share_energy", "gain"])
let trans_rows = derived_csv("transition.csv", ods.select(ren_delta, ["country", "share_2000", "renewables_share_energy", "gain"]))
let mover_svg = plot.bar(movers["country"], movers["gain"],
    #{ "title": `Renewables share gain, 2000—${ren_year}`, "y_label": "percentage points" })
section(`Energy transition (2000—${ren_year})`,
    `Renewables' share of primary energy, biggest gains in percentage points (${trans_rows} countries tracked):` + "\n\n" + table(movers_view, 15) + "\n\n" + chart("transition.svg", mover_svg))
stage("transition", `year ${ren_year}, top gain ${math.round(ods.max(ren_delta["gain"]) * 10.0) / 10.0} pp`)

// ── 8. relationships ─────────────────────────────────────────────────
// The cross-section needs GDP (which trails the calendar by years)
// AND energy coverage in the same year — take the earlier of the two
// frontiers rather than assuming either.
let energy_frontier = latest_covered_year(energy_countries, "energy_per_capita", 120)
let gdp_frontier = latest_covered_year(co2_countries, "gdp", 100)
let both_year = if gdp_frontier < energy_frontier => gdp_frontier else => energy_frontier
let co2_side = cross_section(co2_countries, both_year, ["country", "co2_per_capita", "gdp", "population"])
let with_gdp_pc = ods.with_column(co2_side, "gdp_per_capita",
    ods.cast(co2_side["gdp"], "Float") / ods.cast(co2_side["population"], "Float"))
let energy_side = cross_section(energy_countries, both_year, ["country", "energy_per_capita"])
let joined = ods.drop_null(ods.join(with_gdp_pc, energy_side, "country"))
let r_energy = math.round(stats.corr(joined["co2_per_capita"], joined["energy_per_capita"]) * 1000.0) / 1000.0
let r_gdp = math.round(stats.corr(joined["co2_per_capita"], joined["gdp_per_capita"]) * 1000.0) / 1000.0
let fit = stats.lm(joined["co2_per_capita"], [joined["energy_per_capita"]])
let coefs = ods.to_list(map_get(fit, "coef"))
let slope = math.round(coefs[1] * 100000.0) / 100000.0
let r2 = math.round(map_get(fit, "r2") * 1000.0) / 1000.0
let scatter_svg = plot.scatter(joined["energy_per_capita"], joined["co2_per_capita"],
    #{ "title": `CO2 vs energy per capita, ${both_year}`, "x_label": "kWh per person", "y_label": "t CO2 per person" })
let sorted_by_gdp = ods.sort_by(joined, "gdp_per_capita", true)
let half = ods.n_rows(sorted_by_gdp) / 2
let rich = ods.head(sorted_by_gdp, half)["co2_per_capita"]
let poor = ods.tail(sorted_by_gdp, half)["co2_per_capita"]
let tt = stats.t_test(rich, poor)
let p_raw = map_get(tt, "p_value")
let p_value = if p_raw < 0.001 => "<0.001" else => show(math.round(p_raw * 1000.0) / 1000.0)
section(`Relationships (${both_year}, ${ods.n_rows(joined)} countries)`,
    `Per-capita CO2 correlates with per-capita energy use at **r=${r_energy}** (GDP per capita: r=${r_gdp}). A linear model gives slope ${slope} t per kWh with **R²=${r2}**. The richer half of countries emits more per person than the poorer half (t-test p=${p_value}).` + "\n\n" + chart("energy-co2.svg", scatter_svg))
stage("relationships", `r=${r_energy}, R2=${r2}, n=${ods.n_rows(joined)}`)

// ── 9. report ────────────────────────────────────────────────────────
let bytes = write(cell.get(blocks))
stage("report", `out/report.md (${bytes} bytes), 4 charts, 2 derived CSVs`)
println(`done in ${time.monotonic_ms() - t0} ms — open out/report.md`)
