name = "Olang"
grammar = "olang"
path_suffixes = ["ol", "olang"]
line_comments = ["// "]
tab_size = 4
hard_tabs = false
autoclose_before = ";:.,=}])>"
brackets = [
  { start = "{", end = "}", close = true, newline = true },
  { start = "[", end = "]", close = true, newline = true },
  { start = "(", end = ")", close = true, newline = false },
  { start = "\"", end = "\"", close = true, newline = false, not_in = ["string", "comment"] },
  { start = "'", end = "'", close = true, newline = false, not_in = ["string", "comment"] },
  { start = "`", end = "`", close = true, newline = false, not_in = ["string", "comment"] },
]
