//! crimes — the ultimate workstream: 8.6 million rows, end to end.
//!
//! The full City of Chicago crime record (2001—present, ~2 GB of live
//! CSV) downloaded as part of the run, profiled, mined, and modeled —
//! trend inference, category and rhythm analysis, a chi-square
//! independence test, k-means spatial clustering, and a logistic
//! regression predicting arrests, every algorithm written in olang
//! itself. Outputs land in out/: a markdown report, SVG charts,
//! derived CSVs. data/ and out/ are regenerated by the run and
//! ignored by git.
//!
//! Run:  olang run main.ol      (first run downloads ~2 GB)

use lib.fetch { fetch }
use lib.prep { derive_time, label_share, one_hot }
use lib.ml { train_test_indices, logistic_train, logistic_predict,
             classification_report, auc, kmeans2, normalize }
use lib.report { table, chart, derived_csv, write }

let t0 = time.monotonic_ms()
let t = cell(time.monotonic_ms())
fn stage(name, note) = {
    let now = time.monotonic_ms()
    println(`[${name}] ${now - cell.get(t)} ms — ${note}`)
    cell.set(t, now)
}
let blocks = cell(["# Chicago crime, 2001—present — the full-record workstream",
    `Generated ${dates.today()} by examples/data-processing/crimes/main.ol on the complete City of Chicago crime extract.`])
fn section(title, body) =
    cell.set(blocks, concat(cell.get(blocks), ["## " + title, body]))

// ── 1. fetch: the full record ────────────────────────────────────────
println("fetching the full Chicago crime extract (~2 GB, cached after the first run)...")
let src = unwrap(fetch(
    "https://data.cityofchicago.org/api/views/ijzp-q8t2/rows.csv?accessType=DOWNLOAD",
    fs.join("data", "chicago-crimes.csv"), 1500000000))
stage("fetch", `${map_get(src, "bytes")} bytes (cached=${map_get(src, "cached")})`)

// ── 2. load + profile ────────────────────────────────────────────────
let raw = unwrap(ods.read_csv_file(map_get(src, "path")))
let n_all = ods.n_rows(raw)
let f = ods.select(raw, ["Date", "Primary Type", "Location Description",
    "Arrest", "Domestic", "District", "Year", "Latitude", "Longitude"])
let null_lat = ods.null_count(f["Latitude"])
stage("load", `${n_all} rows x ${ods.n_cols(raw)} cols; ${null_lat} rows lack coordinates`)

// ── 3. derive: month and hour for all 8.6M rows ─────────────────────
let tm = derive_time(ods.to_list(f["Date"]))
let f2 = ods.with_column(ods.with_column(f, "month", ods.series(map_get(tm, "months"))),
    "hour", ods.series(map_get(tm, "hours")))
let arrest_f = ods.cast(f2["Arrest"], "Float")
let overall_rate = math.round(ods.mean(arrest_f) * 1000.0) / 10.0
stage("derive", `month+hour for ${n_all} rows; overall arrest rate ${overall_rate}%`)

// ── 4. the two-decade trend ──────────────────────────────────────────
let complete = ods.filter(f2, f2["Year"] <= 2024)
let by_year = ods.sort_by(ods.group_by(ods.filter(complete, complete["Year"] >= 2001),
    ["Year"], [["n", "count"]]), "Year", false)
let year_fit = stats.lm(ods.cast(by_year["n"], "Float"), [ods.cast(by_year["Year"], "Float")])
let slope = math.round(ods.to_list(map_get(year_fit, "coef"))[1])
let peak_n = ods.max(by_year["n"])
let last_n = ods.to_list(by_year["n"])[ods.n_rows(by_year) - 1]
let trend_svg = plot.line(by_year["Year"], by_year["n"],
    #{ "title": "Reported crimes per year, 2001—2024", "x_label": "year", "y_label": "incidents" })
let yr_rows = derived_csv("by_year.csv", by_year)
section("The two-decade trend",
    `From a peak of **${peak_n}** incidents in a year to **${last_n}** in 2024 — the fitted linear trend loses **${0 - slope} incidents per year** (R²=${math.round(map_get(year_fit, "r2") * 100.0) / 100.0}).` + "\n\n" + chart("trend.svg", trend_svg))
stage("trend", `${yr_rows} years, slope ${slope}/yr`)

// ── 5. what the city reports, and what gets an arrest ────────────────
let with_af = ods.with_column(f2, "arrest_f", arrest_f)
let by_type = ods.sort_by(ods.group_by(with_af, ["Primary Type"], [
    ["n", "count"], ["arrest_rate", "mean", "arrest_f"]]), "n", true)
let top_types = ods.head(by_type, 12)
let type_rows = derived_csv("by_type.csv", by_type)
let types_svg = plot.bar(top_types["Primary Type"], top_types["n"],
    #{ "title": "Twelve most-reported categories, all years", "y_label": "incidents" })
section("Categories and arrest rates",
    `${type_rows} distinct primary types. The twelve most reported, with the share of incidents that led to an arrest:` + "\n\n" + table(top_types, 12) + "\n\n" + chart("types.svg", types_svg))
stage("categories", `${type_rows} types; most-reported ${ods.to_list(top_types["Primary Type"])[0]}`)

// ── 6. the city's rhythm: month and hour ─────────────────────────────
let by_month = ods.sort_by(ods.group_by(f2, ["month"], [["n", "count"]]), "month", false)
let by_hour = ods.sort_by(ods.group_by(f2, ["hour"], [["n", "count"]]), "hour", false)
let rhythm_svg = plot.line(by_hour["hour"], by_hour["n"],
    #{ "title": "Incidents by hour of day, all years", "x_label": "hour", "y_label": "incidents" })
let peak_hour = ods.to_list(ods.sort_by(by_hour, "n", true)["hour"])[0]
let low_month = ods.to_list(ods.sort_by(by_month, "n", false)["month"])[0]
section("The city's rhythm",
    `The hourly curve carries a data-entry artifact worth naming: incidents with unknown times are stamped midnight (and to a lesser degree noon), so hour ${peak_hour} leads on paper. Away from those spikes the evening hours dominate, and summer months out-report winter (the quietest month is ${low_month}).` + "\n\n" + chart("rhythm.svg", rhythm_svg))
stage("rhythm", `peak hour ${peak_hour}`)

// ── 7. independence: arrest x domestic (chi-square) ─────────────────
let dom_f = ods.cast(f2["Domestic"], "Float")
let n_total = to_float(n_all)
let p_arrest = ods.mean(arrest_f)
let p_dom = ods.mean(dom_f)
let with_dom = ods.with_column(with_af, "dom_f", dom_f)
let both = ods.mean(with_dom["arrest_f"] * with_dom["dom_f"]) * n_total
let arrest_only = p_arrest * n_total - both
let dom_only = p_dom * n_total - both
let neither = n_total - both - arrest_only - dom_only
let obs = ods.series([both, arrest_only, dom_only, neither])
let exp = ods.series([
    p_arrest * p_dom * n_total,
    p_arrest * (1.0 - p_dom) * n_total,
    (1.0 - p_arrest) * p_dom * n_total,
    (1.0 - p_arrest) * (1.0 - p_dom) * n_total])
let chi = stats.chi2_test(obs, exp)
let chi_stat = math.round(map_get(chi, "chi2"))
section("Are arrests independent of the domestic flag?",
    `A chi-square test against independence: χ²=**${chi_stat}** (p ${if map_get(chi, "p_value") < 0.001 => "<0.001" else => show(map_get(chi, "p_value"))}) on ${n_all} incidents — arrest and the domestic flag are decisively not independent.`)
stage("chi2", `chi2=${chi_stat}`)

// ── 8. spatial structure: k-means on the recent city ────────────────
let recent = ods.drop_null(ods.select(ods.filter(f2, f2["Year"] >= 2023),
    ["Latitude", "Longitude"]))
let lats = ods.to_list(recent["Latitude"])
let lons = ods.to_list(recent["Longitude"])
let km = kmeans2(lats, lons, 10, 12)
let sizes = map_get(km, "sizes")
let centroids = ods.frame_from_records(map(0..10, (c) => #{
    "cluster": c,
    "lat": math.round(map_get(km, "cx")[c] * 10000.0) / 10000.0,
    "lon": math.round(map_get(km, "cy")[c] * 10000.0) / 10000.0,
    "incidents": sizes[c] }))
let cl_rows = derived_csv("clusters.csv", centroids)
let spatial_svg = plot.scatter(ods.series(map(0..2000, (i) => lons[i * (len(lons) / 2000)])),
    ods.series(map(0..2000, (i) => lats[i * (len(lats) / 2000)])),
    #{ "title": "Incident locations, 2023— (2,000-point sample)", "x_label": "longitude", "y_label": "latitude" })
section("Spatial structure (k-means, k=10, written in olang)",
    `Lloyd's algorithm over **${len(lats)}** recent incidents — ${12} iterations of ${len(lats)} x 10 distance evaluations, all in olang's own loops:` + "\n\n" + table(ods.sort_by(centroids, "incidents", true), 10) + "\n\n" + chart("spatial.svg", spatial_svg))
stage("kmeans", `${len(lats)} points, largest cluster ${ods.max(centroids["incidents"])}`)

// ── 9. predicting arrests: logistic regression in olang ─────────────
let ml_frame = ods.drop_null(ods.select(ods.filter(f2, f2["Year"] >= 2025),
    ["Primary Type", "Arrest", "Domestic", "District", "month", "hour", "Latitude", "Longitude"]))
let n_ml = ods.n_rows(ml_frame)
let labels_all = ods.to_list(ods.cast(ml_frame["Arrest"], "Float"))
let top5 = ods.to_list(ods.head(ods.sort_by(ods.group_by(ml_frame, ["Primary Type"],
    [["n", "count"]]), "n", true), 5)["Primary Type"])
let type_list = ods.to_list(ml_frame["Primary Type"])
let features = concat([
    normalize(map(ods.to_list(ml_frame["hour"]), (h) => to_float(h))),
    normalize(map(ods.to_list(ml_frame["month"]), (m) => to_float(unwrap(str.parse_int(m))))),
    ods.to_list(ods.cast(ml_frame["Domestic"], "Float")),
    normalize(map(ods.to_list(ml_frame["District"]), (d) => to_float(d))),
    normalize(ods.to_list(ml_frame["Latitude"])),
    normalize(ods.to_list(ml_frame["Longitude"]))
], one_hot(type_list, top5))
let split = train_test_indices(n_ml, 5)
let train_idx = map_get(split, "train")
let test_idx = map_get(split, "test")
fn gather(vals, idx) = map(idx, (i) => vals[i])
let train_cols = map(features, (colv) => gather(colv, train_idx))
let test_cols = map(features, (colv) => gather(colv, test_idx))
let train_y = gather(labels_all, train_idx)
let test_y = gather(labels_all, test_idx)
println(`  training: ${len(train_y)} rows x ${len(features)} features x 100 epochs of full-batch gradient descent (pure olang — this is the long stage)`)
let model = logistic_train(train_cols, train_y, 100, 2.0)
let preds = logistic_predict(model, test_cols, len(test_y))
let rep = classification_report(preds, test_y)
let model_auc = math.round(auc(preds, test_y) * 1000.0) / 1000.0
let acc = math.round(map_get(rep, "accuracy") * 1000.0) / 10.0
let base_rate = math.round((1.0 - ods.mean(ods.series(test_y))) * 1000.0) / 10.0
let losses = map_get(model, "loss_curve")
let loss_svg = plot.line(ods.series(map(0..len(losses), (i) => i * 10)), ods.series(losses),
    #{ "title": "Logistic regression training loss", "x_label": "epoch", "y_label": "log loss" })
section("Predicting arrests (logistic regression, written in olang)",
    `Trained on **${len(train_y)}** incidents from 2024— with ${len(features)} features (time, place, domestic flag, one-hot top-5 category), tested on ${len(test_y)} held-out rows: **accuracy ${acc}%** against a ${base_rate}% always-no baseline, **AUC ${model_auc}**, precision ${math.round(map_get(rep, "precision") * 100.0) / 100.0}, recall ${math.round(map_get(rep, "recall") * 100.0) / 100.0}. Full-batch gradient descent, 100 epochs, every arithmetic step written in olang and executed on the bytecode tier — the loss curve is the proof of convergence:` + "\n\n" + chart("loss.svg", loss_svg))
stage("logistic", `n=${n_ml}, acc ${acc}%, AUC ${model_auc}`)

// ── 10. report ───────────────────────────────────────────────────────
let bytes = write(cell.get(blocks))
stage("report", `out/report.md (${bytes} bytes), 5 charts, 3 derived CSVs`)
println(`done in ${math.round(to_float(time.monotonic_ms() - t0) / 100.0) / 10.0} s over ${n_all} rows — open out/report.md`)
